name: Build and Deploy Third Lib

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu_latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        ref: master
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"
    - name: mkdir
      run: |
        mkdir -p build
        cd build
    - name: cmake
      run: |
        cmake ..
    - name: make
      run: |
        make
    - name: workspacefolder
      run: |
        cd ..
    - name: create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
      with:
        tag_name: ${{github.ref}}
        release_name: Release ${{github.ref_name}}
        draft: false
        prerelease: false
    - name: upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
      with:
        upload_url: ${{steps.create_release.outputs.upload_url}}
        asset_path: ./lib/libtrie_tree.a
        asset_name: libtrie_tree.a
        asset_content_type: application/octet-stream